name: Matrix Build Demo

on:
  push:
  workflow_dispatch:
jobs:
  matrix-test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest]
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Print environment info
        run: |
          echo "Running on $RUNNER_OS"
          python --version        
